openapi: 3.0.0
info:
  title: kartoshka-api
  version: 1.0.0
paths:
  /{path+}:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: bba4atdl95ljfrsjs14i
        service_account_id: ajed34lo1545dsks62n9
      parameters:
        - name: path
          in: path
          required: false
          schema:
            type: string
